# Generated by Django 5.0.1 on 2024-02-06 07:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("start_timestamp", models.IntegerField()),
                ("end_timestamp", models.IntegerField()),
                ("user_email", models.EmailField(max_length=254)),
                ("user_name", models.CharField(max_length=255)),
                ("cell_id", models.IntegerField()),
                ("reminded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
